pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
        stage ('Clone Repo'){
            steps {
                sh "git clone https://github.com/jjinnm4real/testRepo_v1.3.git"
                    
            }
        }
        
        stage ('Build') {
            steps {
                dir("testRepo_v1.3/MICA L0 Test1") {
                     sh 'python.exe is_even.py 3 1'
                } 
            }        
        }
        stage('Publish Reports') {
            steps {
                dir("testRepo_v1.3/MICA L0 Test1/") {
                    echo "Set dir"
                }    
                
                
            }    
        }
    }
    
}   
