pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
       
        
        stage ('Run Test') {
            steps {
                dir("testRepo_v1.3/MICA L0 Test1/") {
                    bat "dir.bat"
                }    
            }
        }
    }    
}   
