pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
       
         stage ('Clone GitHub Repo'){
            steps {
                sh "git clone https://github.com/jjinnm4real/testRepo_v1.3.git"
                echo "GitHub v1.3 - MICA Test1 cloned"
                    
            }
        }
        stage ('Clone Bitbucket Repo'){
            steps {
                sh "git clone https://jedmister@bitbucket.org/jedmister/v1.3_coderepo.git"
                 echo "Bitbucket v1.3 - MICA L0 Test1 cloned"
            }
        }    
        stage ('Test') {
            steps {
                dir("testRepo_v1.3/MICA L0 Test1/") {
                    sh 'pwd'
                    sh 'python test_sample.py'
                    
                   
                }    
            }
        }
    }
    post {
        always {
            junit 'build/reports/**/*.xml'
        }
    }
}   
