pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
       
         stage ('Clone GitHub Repo'){
            steps {
                sh "git clone https://github.com/jjinnm4real/testRepo_v1.3.git"
                echo "GitHub v1.3 - MICA Test1 cloned"
                    
            }
        }
        stage ('Clone Bitbucket Repo'){
            steps {
                sh "git clone https://jedmister@bitbucket.org/jedmister/v1.3_coderepo.git"
                 echo "Bitbucket v1.3 - MICA L0 Test1 cloned"
            }
        }    
        stage ('Run Test') {
            steps {
                dir("testRepo_v1.3/MICA L0 Test1/") {
                    sh 'python.exe is_even.py 2 1'
                }    
            }
        }
        stage ('Generate HTML Reports') {
            steps {
                dir("testRepo_v1.3/MICA L0 Test1/") {
                    echo "Directory set to htmlreports"
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: '', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: 'Index'])
                }    
                    
            }
        }    
    }    
}   
