pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
        stage ('Clone Repo'){
            steps {
                sh "git clone https://github.com/jjinnm4real/testRepo_v1.3.git"
            }
        }
        
        stage ('Build') {
            steps {
                dir('testRepo_v1.3/MICA_L0/test1') {
                    bat "dir.bat"
                    

                }    
            }
        }
        
    }
    
}    
