pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
        stage ('Clone GitHub Repo'){
            steps {
                sh "git clone https://github.com/jjinnm4real/testRepo_v1.3.git"
                echo "GitHub testRepo pulled"
                    
            }
        }
                
        stage ('Build') {
            steps {
                dir('testRepo_v1.3/Test3') {
                    sh "python.exe create_json.py"
                }    
                 
            }        
        }
        stage ('Generate Cucumber Report') {
            steps {
                    cucumber buildStatus: 'SUCCESS',
                    reportTitle: 'My Report',
                    fileIncludePattern: '**/behave*.json',
                    trendsLimit: 10,
                    classifications: [
                        [
                            'key': 'Browser',
                            'values': 'Firefox'
                        ]
                    ]
                echo "CUCUMBER tests report: ${BUILD_URL}cucumber-html-reports_53e47127-7e8c-38f4-bc2a-429191699127/overview-features.html"
            }
        }    
                
        
    }
    
      
    
}   
