pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
        stage ('Clone Repo'){
            steps {
                sh "git clone https://github.com/jjinnm4real/testRepo_v1.3.git"
                    
            }
        }
        
        stage ('Build') {
            steps {
                dir('testRepo_v1.3/Test2') {
                    sh "python.exe hello_world.py"
                }    
                 
            }        
        }
        stage ('Generate HTML Report') {
            steps {
                    cucumber buildStatus: 'SUCCESS',
                    reportTitle: 'My Report',
                    fileIncludePattern: '**/test2*.json',
                    trendsLimit: 10,
                    classifications: [
                        [
                            'key': 'Browser',
                            'values': 'Firefox'
                        ]
                    ]
            }
        }    
                
        
    }
    
      
    
}   
