pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
        
      stage ('Start Test1 Pipeline') {
            steps {
                build job: 'Test1', propagate: true, wait: true
            }
        }
      
    }          
  
}
