pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
        
        stage ('Start Test1 Pipeline') {
            steps {
                build job: 'Test1', propagate: true, wait: true
            }
        }
        stage ('Start Test2 Pipeline') {
            steps {
                build job: 'Test2', propagate: true, wait: true
            }
        }    
      
        stage ('Generate Cucumber Report') {
            steps {
                dir("testRepo_v1.3/v1.3-build-all-tests/") {
                    cucumber buildStatus: 'SUCCESS',
                    reportTitle: 'My Report',
                    fileIncludePattern: '**/*.json',
                    trendsLimit: 10,
                    classifications: [
                        [
                            'key': 'Browser',
                            'values': 'Firefox'
                        ]
                    ]
                    echo "CUCUMBER tests report: ${BUILD_URL}cucumber-reports_53e47127-7e8c-38f4-bc2a-429191699127"
                }
            }    
        }    
    }          
  
}
